#!/bin/sh
# mkarch.sh — build an Arch Linux package for cli-zapp.
#
# An Arch package is a zstd-compressed tar with a fixed member order:
# .PKGINFO, .BUILDINFO, .MTREE, .INSTALL, then the files.
#
# PKGBUILD is the source of truth. It cannot be run standalone, though — it is a
# shell fragment that makepkg executes with a dozen variables and helpers defined.
# So there are two paths:
#
#   1. `makepkg` — the faithful one. It validates the PKGBUILD itself, which is the
#      whole reason to ship a PKGBUILD rather than a hand-written archive. Needs
#      Arch tooling.
#   2. Direct construction — works anywhere Go and tar exist, but proves nothing
#      about the PKGBUILD.
#
# This script prefers (1) and falls back to (2). A PKGBUILD that is only ever
# exercised by hand-built code is a PKGBUILD that rots.
#
# Usage: mkarch.sh <version> <distdir> <commit> <build-date> <ldflags>
#        ARCH=x86_64|aarch64  to choose the architecture (default x86_64)

set -eu

version=${1:?version}
dist=${2:?distdir}
commit=${3:?commit}
build_date=${4:?build-date}
ldflags=${5:?ldflags}

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
bin=cli-zapp
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT INT TERM

epoch=${SOURCE_DATE_EPOCH:-$(git -C "$root" log -1 --format=%ct 2>/dev/null || date +%s)}

# Arch's own architecture names, which are not Go's.
case "${ARCH:-x86_64}" in
x86_64) goarch=amd64; pkgarch=x86_64 ;;
aarch64) goarch=arm64; pkgarch=aarch64 ;;
*) echo "mkarch.sh: unsupported ARCH '${ARCH:-x86_64}'" >&2; exit 1 ;;
esac

pkgver=$(printf '%s' "$version" | sed 's/^v//' | tr '/' '_')

# ---------------------------------------------------------------- makepkg path
if command -v makepkg >/dev/null 2>&1 && [ -f "$root/packaging/arch/PKGBUILD" ]; then
	echo "==> makepkg $bin-$pkgver-1-$pkgarch"
	# makepkg is run from a scratch copy of the recipe, never from the checkout.
	#
	# This is not tidiness. makepkg creates $pkgdir with mode 0711 while building and
	# restores it on success; when a build fails partway it leaves the directory
	# unreadable. That directory would sit inside the repository, and `go build ./...`,
	# `go vet ./...` and `go test ./...` all walk the whole tree — so one failed
	# `make package-arch` would leave the Go toolchain unable to read its own module.
	# Building elsewhere makes that impossible rather than merely unlikely.
	scratch="$work/pkgsrc"
	mkdir -p "$scratch"
	cp "$root/packaging/arch/PKGBUILD" "$scratch/"
	if [ -f "$root/packaging/arch/$bin.install" ]; then
		cp "$root/packaging/arch/$bin.install" "$scratch/"
	fi

	( cd "$scratch" && \
	  makepkg \
	    --nodeps \
	    --noconfirm \
	    --cleanbuild \
	    --clean \
	    --holdver \
	    --noprogressbar \
	    env \
	      "SRC_DIR=$root" \
	      "PKGVER_OVERRIDE=$pkgver" \
	      "COMMIT=$commit" \
	      "BUILD_DATE=$build_date" \
	      "PKGDEST=$work/out" )

	built=$(ls -1t "$work"/out/*.pkg.tar.* 2>/dev/null | head -1 || true)
	if [ -n "$built" ]; then
		mkdir -p "$dist"
		cp "$built" "$dist/"
		echo "    $dist/$(basename "$built")"
		exit 0
	fi
	echo "    makepkg produced no package; falling back to direct construction" >&2
fi

# --------------------------------------------------------------- direct path
echo "==> direct build $bin-$pkgver-1-$pkgarch"

pkg="$work/$bin-$pkgver-1-$pkgarch"
mkdir -p "$pkg/usr/bin" "$pkg/usr/share/doc/$bin" "$pkg/usr/share/licenses/$bin"

echo "    compiling linux/$goarch"
GOOS=linux GOARCH=$goarch CGO_ENABLED=0 \
	go build -buildvcs=false -trimpath -ldflags "$ldflags" \
	-o "$pkg/usr/bin/$bin" "$root/cmd/$bin"

install -m 0644 "$root/LICENSE" "$pkg/usr/share/licenses/$bin/LICENSE"
install -m 0644 "$root/README.md" "$pkg/usr/share/doc/$bin/README.md"
if [ -d "$root/docs" ]; then
	cp -r "$root/docs" "$pkg/usr/share/doc/$bin/docs"
	find "$pkg/usr/share/doc/$bin/docs" -type f -exec chmod 0644 {} +
fi

installed_size=$(du -sb "$pkg" | cut -f1)

# .PKGINFO and .BUILDINFO are both `key = value`, and pacman reads the latter for
# `pacman -Qii`. The two differ only in intent upstream; emitting both keeps
# `makepkg`'s expectations satisfied for the fallback path.
cat > "$pkg/.PKGINFO" <<EOF
# Generated by scripts/mkarch.sh.
pkgname = $bin
pkgbase = $bin
pkgver = $pkgver
pkgdesc = Keyboard-driven WhatsApp client for the terminal
url = https://github.com/ldgnu/cli-zapp
builddate = $epoch
packager = cli-zapp maintainers <maintainers@cli-zapp.invalid>
size = $installed_size
arch = $pkgarch
license = MIT
provides = $bin
makedepends = go
EOF

cp "$pkg/.PKGINFO" "$pkg/.BUILDINFO"

# .INSTALL records the paths the package owns, so `pacman -Ql` works even though
# the file list comes from the archive itself.
cat > "$pkg/.INSTALL" <<EOF
$bin
EOF

# .MTREE: gsha256, which is what `bsdtar -z sha256 --format=mtree` emits and what
# `pacman -Qkk` verifies against. Generated by bsdtar when available, because the
# field order and the space-separated layout are libarchive's to define and are not
# worth hand-reimplementing.
if command -v bsdtar >/dev/null 2>&1; then
	# The metadata members are excluded: they describe the package rather than
	# belonging to it, and including them makes `pacman -Qkk` report drift on files
	# the user never installed.
	( cd "$pkg" && bsdtar -czf .MTREE --format=mtree -z sha256 \
		--options '!uid,!gid,!uname,!gname,!time' \
		--exclude ./.MTREE --exclude ./.PKGINFO --exclude ./.BUILDINFO \
		--exclude ./.INSTALL usr )
else
	echo "    bsdtar not found: omitting .MTREE (pacman -Qkk will not verify)" >&2
fi

out="$dist/$bin-$pkgver-1-$pkgarch.pkg.tar.zst"
mkdir -p "$dist"
rm -f "$out"

# Member order is fixed by the format. --sort=name and a fixed mtime are what make
# two builds of one commit byte-identical.
tar --sort=name --owner=0 --group=0 --numeric-owner --mtime="@$epoch" \
	--zstd -cf "$out" -C "$pkg" \
	.PKGINFO .BUILDINFO .MTREE .INSTALL usr 2>/dev/null \
	|| tar --sort=name --owner=0 --group=0 --numeric-owner --mtime="@$epoch" \
		--zstd -cf "$out" -C "$pkg" .PKGINFO .BUILDINFO .INSTALL usr

echo "    $out"